'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Tbl_Prescription
    Public Property ID_Prescription As Long
    Public Property DateAusculte As Nullable(Of Date)
    Public Property DescriptionDiagnostique As String
    Public Property DescriptionSymptome As String
    Public Property LieuConsultation As String
    Public Property PoidsPatient As Nullable(Of Decimal)
    Public Property TaillePatient As Nullable(Of Decimal)
    Public Property CodePatient As Nullable(Of Long)
    Public Property CodeMedecin As Nullable(Of Long)

    Public Overridable Property Tbl_MedicamentPrescrit As ICollection(Of Tbl_MedicamentPrescrit) = New HashSet(Of Tbl_MedicamentPrescrit)
    Public Overridable Property Tbl_Individu As Tbl_Individu
    Public Overridable Property Tbl_Individu1 As Tbl_Individu

End Class
