'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Tbl_Privilege
    Public Property ID_Privilege As Short
    Public Property Libelle As String

    Public Overridable Property Tbl_Utilisateur As ICollection(Of Tbl_Utilisateur) = New HashSet(Of Tbl_Utilisateur)

End Class
