'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Tbl_Institution
    Public Property ID_Institution As Long
    Public Property Nom As String
    Public Property Email As String
    Public Property EmailResponsable As String
    Public Property Adresse As String
    Public Property NomResponsable As String
    Public Property Telephone As String
    Public Property TelephoneResponsable As String
    Public Property ID_TypeInstitution As Nullable(Of Short)
    Public Property ID_localisation As Nullable(Of Long)

    Public Overridable Property Tbl_TypeInstitution As Tbl_TypeInstitution
    Public Overridable Property Tbl_Ville As Tbl_Ville
    Public Overridable Property Tbl_TestPrescrit As ICollection(Of Tbl_TestPrescrit) = New HashSet(Of Tbl_TestPrescrit)
    Public Overridable Property Tbl_MedicamentPrescrit As ICollection(Of Tbl_MedicamentPrescrit) = New HashSet(Of Tbl_MedicamentPrescrit)

End Class
