'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Tbl_TestPrescrit
    Public Property CodeTestLaboratoire As Long
    Public Property ID_Institution As Long
    Public Property isExecute As Nullable(Of Boolean)

    Public Overridable Property Tbl_Institution As Tbl_Institution
    Public Overridable Property Tbl_TestLaboratoire As Tbl_TestLaboratoire

End Class
