'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Tbl_MedicamentPrescrit
    Public Property ID As Long
    Public Property CodeMedicament As Long
    Public Property CodePrescription As Long
    Public Property Debut As Nullable(Of Date)
    Public Property Dosage As String
    Public Property EffeSecondaire As String
    Public Property isExecute As Nullable(Of Boolean)
    Public Property Fin As Nullable(Of Date)
    Public Property ID_Institution As Nullable(Of Long)
    Public Property cout_medicament As Nullable(Of Decimal)

    Public Overridable Property Tbl_Institution As Tbl_Institution
    Public Overridable Property Tbl_Medicament As Tbl_Medicament
    Public Overridable Property Tbl_Prescription As Tbl_Prescription

End Class
