'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Tbl_SpecialisationMedecin
    Public Property CodeSpecialisation As Long
    Public Property CodeIndividu As Long
    Public Property ID_specialisation_medecin As Long

    Public Overridable Property Tbl_Specialisation As Tbl_Specialisation
    Public Overridable Property Tbl_Individu As Tbl_Individu

End Class
