'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Tbl_Individu
    Public Property ID_Individu As Long
    Public Property Nom As String
    Public Property Prenom As String
    Public Property NomPere As String
    Public Property NomMere As String
    Public Property DateNaissance As Nullable(Of Date)
    Public Property LieuNaissance As String
    Public Property Identification As String
    Public Property GroupeSanguin As String
    Public Property isMedecin As Nullable(Of Boolean)
    Public Property VilleNaissance As Nullable(Of Long)
    Public Property ID_Sexe As Nullable(Of Short)
    Public Property addresse As String

    Public Overridable Property Tbl_Sexe As Tbl_Sexe
    Public Overridable Property Tbl_Ville As Tbl_Ville
    Public Overridable Property Tbl_Prescription As ICollection(Of Tbl_Prescription) = New HashSet(Of Tbl_Prescription)
    Public Overridable Property Tbl_Prescription1 As ICollection(Of Tbl_Prescription) = New HashSet(Of Tbl_Prescription)
    Public Overridable Property Tbl_SpecialisationMedecin As ICollection(Of Tbl_SpecialisationMedecin) = New HashSet(Of Tbl_SpecialisationMedecin)
    Public Overridable Property Tbl_Utilisateur As ICollection(Of Tbl_Utilisateur) = New HashSet(Of Tbl_Utilisateur)

End Class
