'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Tbl_TestLaboratoire
    Public Property ID_TestLaboratoire As Long
    Public Property CodeInternational As String
    Public Property Description As String

    Public Overridable Property Tbl_TestPrescrit As ICollection(Of Tbl_TestPrescrit) = New HashSet(Of Tbl_TestPrescrit)

End Class
