'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Tbl_Departement
    Public Property ID_Departement As Short
    Public Property Libelle As String

    Public Overridable Property Tbl_Ville As ICollection(Of Tbl_Ville) = New HashSet(Of Tbl_Ville)

End Class
